// Package strtab handles the .strtab sidecar file.
//
// Format: plain text, one record per line:
//
//	<xxhash64_hex>\t<canonical_path>
//
// Lines starting with '#' are comments. Always sorted by hash for diffability.
// Example:
//
//	# gtar string table
//	# generated by gtartool - do not edit path column (breaks lookup)
//	1a2b3c4d5e6f7a8b	assets/meshes/barrel.mesh
//	deadbeefcafebabe	data/config.cbor
package strtab

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/nerdrogue/gtartool/gtar"
)

// Write generates a .strtab file alongside the archive.
// paths is the list of original (pre-canonicalization) paths.
func Write(strtabPath string, paths []string) error {
	type record struct {
		hash uint64
		path string
	}

	records := make([]record, 0, len(paths))
	seen := make(map[uint64]bool)
	for _, p := range paths {
		h := gtar.HashPath(p)
		if seen[h] {
			return fmt.Errorf("hash collision or duplicate path: %q", p)
		}
		seen[h] = true
		records = append(records, record{hash: h, path: gtar.CanonicalPath(p)})
	}

	sort.Slice(records, func(i, j int) bool {
		return records[i].hash < records[j].hash
	})

	f, err := os.Create(strtabPath)
	if err != nil {
		return fmt.Errorf("create strtab: %w", err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "# gtar string table")
	fmt.Fprintln(w, "# generated by gtartool -- do not edit the hash column")
	for _, r := range records {
		fmt.Fprintf(w, "%016x\t%s\n", r.hash, r.path)
	}
	return w.Flush()
}

// Load reads a .strtab file and returns a hash->path map.
func Load(strtabPath string) (map[uint64]string, error) {
	f, err := os.Open(strtabPath)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	out := make(map[uint64]string)
	sc := bufio.NewScanner(f)
	lineNum := 0
	for sc.Scan() {
		lineNum++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "\t", 2)
		if len(parts) != 2 {
			return nil, fmt.Errorf("strtab line %d: expected <hash>\\t<path>, got %q", lineNum, line)
		}
		var h uint64
		if _, err := fmt.Sscanf(parts[0], "%016x", &h); err != nil {
			return nil, fmt.Errorf("strtab line %d: bad hash %q: %w", lineNum, parts[0], err)
		}
		out[h] = strings.TrimSpace(parts[1])
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return out, nil
}
